### ISSUE TITLE
Several logical networks

### ISSUE THREAD

**Issue by ignogueiras** [cni-genie/CNI-Genie#161]
Hi, I am trying to use cni-genie to create multiple subnets under one cni-plugin.
I created two logical networks, weave-1 and weave-2, using

`plugin: "weave"
  sub_subnet: "10.35.0.0/24"`

and

`plugin: "weave"
  sub_subnet: "10.40.0.0/16"`

for each one, same cni-plugin, different cidr range.

It seems to work as expected, networks are created and i can launch pods in them setting

`networks: weave-1`

 or

 `networks: weave-2` 

as pod annotation.

The problems starts when I try to use several logical networks in the same pod.
If I configure it like:

`networks: weave-1,weave-2`

the pod only gets an interface in the last one. I suspect it try to use the same interface name for them all (eth0) and first ones are overwritten.

In a example at CNI-Genie/sampleyamls/network-crd-yamls/pod-multi-networks.yaml I seen it defined as 

`networks: net1:eth0,net2:eth4`

 setting the interface name manually. If I try this approach the pod fails to launch, the only info I got is from kubernetes events, saying the last interface name I set is already in use

 `Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "469b0044e8427f7659abf93ea425126b02b17df04c83bf8cf370d9edaec68c33" network for pod "busybox-weave2": NetworkPlugin cni failed to set up pod "busybox-weave2_default" network: CNI Genie Add IP internal error: Repeated request for same interface name: eth4, result: %!!(MISSING)s(<nil>)`

Is it not possible to use several logical networks in the same pod?

**Comment by sushanthakumar** [comment]
@ignogueiras , you are right, It is designed to support multiple logical networks for same pod, we shall investigate it and update, thanks

**Comment by sushanthakumar** [comment]
@ignogueiras , with the help of very detailed info provided by you, we have fixed this issue and merged to master. You can reinstall genie and check this scenario, lets close this issue after verify, thanks

**Comment by ignogueiras** [comment]
Hi again, @sushanthakumar 
I just tested the new version and it seems to work correctly.
I am still facing some problems trying to deploy a pod with two logical networks, but I think this is cni plugin (weave) fault.

Maybe you can point me to some documentation about creating networks and using them with cni-genie? I was following a trial-and-error process based on a couple of sample .yamls from the repository, since I have not been able to find more complete documentation.

For the rest, I believe that this issue can be closed. Good job!

**Comment by ignogueiras** [comment]
Not sure if directly related or new issue, but I am still unable to launch pod using two logical networks.
Same scenario as before:
two logical networks, weave-1 and weave-2, using

`plugin: "weave" sub_subnet: "10.35.0.0/24"`

and

`plugin: "weave" sub_subnet: "10.40.0.0/16"`

pods using weave-1 OR weave-2 run flawlessly, but if I assign both networks to the same pod it fails to launch. Message in kubernetes events says:

```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c539f3d2e34535941fa
d4c78fd32fea9b1eeb931f3b0a85332ee28237685dfd4" network for pod "busybox-weave-3": NetworkPlugin cni failed to set up pod "busybox-weave-3_default" network: CNI Genie Add IP internal error: error setting u
p routes: failed to add route '{0.0.0.0 00000000} via 10.40.0.0 dev eth1': invalid argument, result: %!!(MISSING)s(<nil>)
```

I tried using other cni plugins, to verify it is not a weave issue. With canal and flannel I see similar behavior: pod with one logical network seems to run with no problems, but if I set it to use two of them it fails. In this case the fail is a little different: pod gets to run, and then it crashes continuously. Executing `ip addr` in pod I can see it gets IP address in the second interface, but not in the first one.

Thanks for your patience!

**Comment by sushanthakumar** [comment]
@ignogueiras , you can share the logical network yaml (2 networks) and pod yaml contents, we will check it

**Comment by ignogueiras** [comment]
Sure, these are the files I am using:
[logicalnetworkexamples.zip](https://github.com/Huawei-PaaS/CNI-Genie/files/2781963/logicalnetworkexamples.zip)

Weave range is `10.32.0.0/12`, so I set two subnets as `10.35.0.0/24` and `10.40.0.0/16`.
For canal, this kubernetes was initialized with `pod-cidr=192.168.0.0/24`, so I split this range in two, `192.168.0.0/25` and `192.168.0.128/25`.
This is not a real scenario, just for testing purposes.

**Comment by sushanthakumar** [comment]
In this case, we are trying to get 2 ip addresses(diff subnet) from weave plugin for same pod. But weave does not support giving multiple ip for same pod. That is the rootcause for this issue. Flannel supports multiple ips for same pod but does not supports dynamic subnet input :(

**Comment by ignogueiras** [comment]
I was testing [this pull request in weave](https://github.com/weaveworks/weave/pull/3343) which allows to assign several weave interfaces to the same pod. It "seems" to work, but it can be it is weaves fault.

In this case, can you recommend any cni plugin which allow me to do this? Do you have any document about the compatibility of the different cni plugins with the features in cni-genie?

In any case, if this is a problem of the underlying cni-plugins and not cni-genie related this issue can be closed.

Thank you!

**Comment by sushanthakumar** [comment]
Closing this issue as of now, you can contact us for any further help/issues
